# Generated by Django 5.0.3 on 2024-03-12 10:51

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_passwordresettoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetTokenModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "expired",
                    models.DateTimeField(
                        auto_created=True,
                        default=datetime.datetime(2024, 4, 11, 10, 51, 55, 258535, tzinfo=datetime.timezone.utc),
                        editable=False,
                        verbose_name="Дата истекания",
                    ),
                ),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False, verbose_name="Токен")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Токен для сброса пароля",
                "verbose_name_plural": "Токены для сброса пароля",
            },
        ),
        migrations.DeleteModel(
            name="PasswordResetToken",
        ),
    ]
