# Generated by Django 5.0.3 on 2024-03-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_passwordresettoken"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PasswordResetToken",
            new_name="PasswordResetTokenModel",
        ),
        migrations.AlterModelOptions(
            name="passwordresettokenmodel",
            options={"verbose_name": "Токен для сброса пароля", "verbose_name_plural": "Токены для сброса пароля"},
        ),
    ]
