# Generated by Django 5.0.3 on 2024-03-12 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_passwordresettokenmodel_delete_passwordresettoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresettokenmodel",
            name="expired",
            field=models.DateTimeField(
                auto_created=True,
                default=datetime.datetime(2024, 4, 11, 13, 9, 55, 957644, tzinfo=datetime.timezone.utc),
                verbose_name="Дата истекания",
            ),
        ),
    ]
