# Generated by Django 5.0.3 on 2024-03-15 10:51

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_passwordresettokenmodel_expired"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresettokenmodel",
            name="expired",
            field=models.DateTimeField(
                auto_created=True, default=users.models._get_password_expired_time, verbose_name="Дата истекания"
            ),
        ),
    ]
