services:
  celery:
    restart: always
    build:
      dockerfile: Dockerfile
    command: "celery -A project worker -l info"
    env_file:
      - ".env"
    environment:
      CELERY_BROKER_URL: "redis://redis"
      CELERY_RESULT_BACKEND: "redis://redis"
      DB_HOST: "postgres"
    depends_on:
      - redis
      - postgres
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
    volumes:
      - ./database:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -d ${DB_NAME} -U ${DB_USER}"
      interval: 5s
      timeout: 10s
      retries: 120
  redis:
    image: redis:alpine
    ports:
      - 6379:6379