# Generated by Django 5.0.3 on 2024-03-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParameterModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cat_id", models.CharField(max_length=4, verbose_name="Идентификатор пакета CAN шины")),
                ("data_length", models.CharField(max_length=50, verbose_name="Длинна")),
                ("length", models.CharField(max_length=50, verbose_name="Длина занимаемая значением")),
                ("name", models.CharField(max_length=100, verbose_name="Наименование")),
                (
                    "rus_name",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="Наименование на русском"),
                ),
                ("scaling", models.CharField(max_length=100, verbose_name="Коэффициент")),
                ("range", models.CharField(max_length=100, verbose_name="Диапазон")),
                ("spn", models.IntegerField(verbose_name="SPN")),
                ("date", models.DateTimeField(auto_now=True, verbose_name="Дата записи")),
                ("status_delete", models.BooleanField(default=False, verbose_name="Статус удаления")),
            ],
            options={
                "verbose_name": "Параметр",
                "verbose_name_plural": "Параметры",
            },
        ),
        migrations.DeleteModel(
            name="Parameter",
        ),
    ]
