# Generated by Django 5.0.3 on 2024-04-12 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_bufferedparametermodel_parametermodel_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parametermodel",
            options={"ordering": ["id"], "verbose_name": "Параметр", "verbose_name_plural": "Параметры"},
        ),
        migrations.CreateModel(
            name="SyncLoggingModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateTimeField(auto_now=True, verbose_name="Дата синхронизации")),
                (
                    "new_params",
                    models.ManyToManyField(
                        to="backend.bufferedparametermodel", verbose_name="Параметры добавленные пользователем"
                    ),
                ),
                (
                    "params_marked_to_delete",
                    models.ManyToManyField(
                        to="backend.parametermodel", verbose_name="Параметры помеченные на удаление"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Логер синхронизации",
                "verbose_name_plural": "Логеры синхронизации",
            },
        ),
    ]
