# Generated by Django 5.0.3 on 2024-04-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_alter_parametermodel_options_syncloggingmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="bufferedparametermodel",
            name="sync_with_main_table",
            field=models.BooleanField(default=False, verbose_name="Синхронизировано с основной таблицей"),
        ),
    ]
