"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

from typing_extensions import NamedTuple

from project.utils import EnvSettings

ENV_SETTINGS = EnvSettings()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-h()!_a*658bw$=7=!vb^iz%8k8srxdkrfo&e!68xn2f0^@4&hb"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ENV_SETTINGS.ALLOWED_HOSTS

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.sites",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "users",
    "backend",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
]

ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": ENV_SETTINGS.DB_NAME,
        "USER": ENV_SETTINGS.DB_USER,
        "PASSWORD": ENV_SETTINGS.DB_USER_PASSWORD,
        "HOST": ENV_SETTINGS.DB_HOST,
        "PORT": ENV_SETTINGS.DB_PORT,
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "ru"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "users.UserModel"

# Rest Framework settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ("rest_framework_simplejwt.authentication.JWTAuthentication",),
}

# Simple JWT settings
SIMPLE_JWT = {"ACCESS_TOKEN_LIFETIME": ENV_SETTINGS.ACCESS_TOKEN_LIFETIME}

# Password Reset Token settings

PASSWORD_RESET_TOKEN_LIFETIME = ENV_SETTINGS.PASSWORD_RESET_TOKEN_LIFETIME

# CELERY settings

CELERY_BROKER_URL = ENV_SETTINGS.CELERY_BROKER_URL
CELERY_RESULT_BACKEND = ENV_SETTINGS.CELERY_RESULT_BACKEND
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# Email settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = True
EMAIL_HOST = ENV_SETTINGS.EMAIL_HOST
EMAIL_PORT = ENV_SETTINGS.EMAIL_PORT
EMAIL_HOST_USER = ENV_SETTINGS.EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = ENV_SETTINGS.EMAIL_HOST_PASSWORD

# MESSAGES
DEFAULT_PASSWORD_RESET_MESSAGE = (
    "Сообщение с ссылкой для сброса пароля было отправлено на указанный email адрес.\n"
    "Обратите внимание что данное сообщение будет отправлено в случае если такая учетная запись существует."
)

# Sites settings
SITE_ID = 1

# CORS
CORS_ALLOW_ALL_ORIGINS = True
